server:
  port: 8800
  servlet:
    context-path:
    session:
      timeout: 7200s
spring:
  mvc:
    static-path-pattern: /**
    date-format: yyyy-MM-dd
    favicon:
      enabled: true
    thymeleaf:
      encoding: UTF-8
      cache: false
      mode: HTML
      prefix: classpath:/templates/
      suffix: .html
  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: yao1992
    url: jdbc:mysql://localhost:3306/bookman?characterEncoding=utf-8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: BookHikariPool
      maximum-pool-size: 12
      connection-timeout: 60000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 50MB
# mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
# 文件上传路径
web:
  upload:
    path: D:/upload/
